name: Docker release build
on: [push]

jobs:
  build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
    - name: checkout master
      uses: actions/checkout@master
      with:
        name: grayudu
    - name: build docker
      run: |
        docker build -t simpleweb .
    - name: docker login
      uses: actions/docker/login@master
      env:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
        args: push grayudu/simpleweb
